name: ESLint Analysis

on:
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
      
    - name: Run eslint
      run: yarn lint
