name: ESLint Analysis

on:
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: yarn install
      
    - name: Run eslint
      run: yarn lint
