name: ESLint Analysis

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: yarn install

    - uses: eslint/github-action@v0
