name: ESLint Analysis

on:
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS 16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install dependencies
        run: yarn install
        
      - uses: a-b-r-o-w-n/eslint-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "src/**/*"
          ignore: "*.svg, *.scss"
          extensions: ".js,.ts,.tsx"
          working-directory: "./fithm_front"
          quiet: "false"
